# Generated by Django 5.2.6 on 2025-09-27 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_alter_catagory_options_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='catagory',
            new_name='category',
        ),
    ]
